# Site settings
title: "Devin McGeehan Muchmore"
bye_message: [Source](https://github.com/devintmm/devintmm.github.io)
baseurl: 
url: 

# Header settings


# Build settings
markdown: kramdown
permalink: /:categories/:title/
